#!/bin/sh


for input in "$@";
do
   if [ -d "$input" ]; then 
     echo "modify:  $input, is a directory."
   elif [ -x "$input" ]; then
     echo "modify:  $input, cannot edit executables"
   else
     echo "modify:  $input, filetype not supported"
   fi
done
