#!/bin/sh
name="Cameron Peete"

weekday=`date +'%A'`
month=`date +'%b'`
dayNum=`date +'%d'`
year=`date +'%Y'`
hour=`date +'%H'`
min=`date +'%M'`

dateTime="$weekday, $month $dayNum: $hour$min"

#echo "$weekday"
#echo "$month"
#echo "$dayNum"
#echo "$year"
#echo "$hour"
#echo "$min"

echo "$dateTime"

if [ $# -eq 0 ]; then
   echo "usage:  modify filename [filename ...]"
fi

for input
do
   if [ -d "$input" ]; then 
     echo "modify:  $input, is a directory."
   elif [ -x "$input" ]; then
     echo "modify:  $input, cannot edit executables"
   elif file "$input" | grep -q "ASCII"; then
    echo "It is ASCII Text"
ed -s $input << END
a
Modified on: $dateTime
Modified by: $name
.
w
q
END
   else
     echo "modify:  $input, filetype not supported"
   fi
done
